[[librealsense]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3b4aaf5179795ad55b5aba72e0159590054928a9"
os = "macos"

    [[librealsense.download]]
    sha256 = "7506254c6351247648e8457fdaa20165b6f640ead81d8445564fafab2cff9fd5"
    url = "https://github.com/JuliaBinaryWrappers/librealsense_jll.jl/releases/download/librealsense-v2.32.1+0/librealsense.v2.32.1.x86_64-apple-darwin14-cxx11.tar.gz"
[[librealsense]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9845530ac9f3e536f2423f6026ca9c1a35150af0"
libc = "glibc"
os = "linux"

    [[librealsense.download]]
    sha256 = "2ef22ebe62e1e4d39b6678d27f0fc12c6d3c54bf29de2bace218dfd17d62b8a8"
    url = "https://github.com/JuliaBinaryWrappers/librealsense_jll.jl/releases/download/librealsense-v2.32.1+0/librealsense.v2.32.1.i686-linux-gnu-cxx03.tar.gz"
[[librealsense]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "088b0dc2e568f22cbacef10b1b3f84f27e167d55"
libc = "glibc"
os = "linux"

    [[librealsense.download]]
    sha256 = "58c0373e12a8857fc89293bf3812cdd346559fd974de7d7b377fa30f5fa279c4"
    url = "https://github.com/JuliaBinaryWrappers/librealsense_jll.jl/releases/download/librealsense-v2.32.1+0/librealsense.v2.32.1.aarch64-linux-gnu-cxx03.tar.gz"
[[librealsense]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f121500f30d5fb2cc776a3ec131243f27a61ffc9"
libc = "glibc"
os = "linux"

    [[librealsense.download]]
    sha256 = "47332155f4c7f0369a6efd7a5e67b5648e18f291a69f2386224499329a4da402"
    url = "https://github.com/JuliaBinaryWrappers/librealsense_jll.jl/releases/download/librealsense-v2.32.1+0/librealsense.v2.32.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[librealsense]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2bb64a74e524cfe407fcbb81f82569b51f0235f2"
libc = "glibc"
os = "linux"

    [[librealsense.download]]
    sha256 = "1cbf52fd195979d43ec7c3b5700475f1d8ebca8d8cb7921b05c2d0b7bb42d980"
    url = "https://github.com/JuliaBinaryWrappers/librealsense_jll.jl/releases/download/librealsense-v2.32.1+0/librealsense.v2.32.1.x86_64-linux-gnu-cxx11.tar.gz"
[[librealsense]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1d557005700b28ebc38365ddc98ac13dc389d01c"
os = "macos"

    [[librealsense.download]]
    sha256 = "78566e67bc376bbd7ebe9a395a19656e406c34cde78d56b10c9d9fac5f932247"
    url = "https://github.com/JuliaBinaryWrappers/librealsense_jll.jl/releases/download/librealsense-v2.32.1+0/librealsense.v2.32.1.x86_64-apple-darwin14-cxx03.tar.gz"
[[librealsense]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ff056d2f090df6b3e8587aaab65f5d190dbd081d"
libc = "glibc"
os = "linux"

    [[librealsense.download]]
    sha256 = "bbba8d76f3a7e1ce265905740bd710dfc969299212a6dc025f05a05aa505287d"
    url = "https://github.com/JuliaBinaryWrappers/librealsense_jll.jl/releases/download/librealsense-v2.32.1+0/librealsense.v2.32.1.aarch64-linux-gnu-cxx11.tar.gz"
[[librealsense]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3de29c953d44c716dff368c3ad63035982f03057"
libc = "glibc"
os = "linux"

    [[librealsense.download]]
    sha256 = "4f19f8e4053365cba71320fdf68cc4f771ceefe86d28789747f38d0d14ede747"
    url = "https://github.com/JuliaBinaryWrappers/librealsense_jll.jl/releases/download/librealsense-v2.32.1+0/librealsense.v2.32.1.i686-linux-gnu-cxx11.tar.gz"
[[librealsense]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ab024534f70c2bf6822c5aedbcce50ee146d48eb"
libc = "glibc"
os = "linux"

    [[librealsense.download]]
    sha256 = "100ae83e4995efdb08e2e94e6b37a373db460a582683fa77c1614b4f3a548d94"
    url = "https://github.com/JuliaBinaryWrappers/librealsense_jll.jl/releases/download/librealsense-v2.32.1+0/librealsense.v2.32.1.x86_64-linux-gnu-cxx03.tar.gz"
[[librealsense]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "67390f75c008c4a1cbf1ebad4139b2082bdd45a6"
libc = "glibc"
os = "linux"

    [[librealsense.download]]
    sha256 = "d64187ef4b38806a836dbc943eec9561f8ea6d0dee622bdcd3cbbacd7f9622c4"
    url = "https://github.com/JuliaBinaryWrappers/librealsense_jll.jl/releases/download/librealsense-v2.32.1+0/librealsense.v2.32.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
