[[librealsense]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "119a1750205173da4094861fa444e0dcf4457d46"
libc = "glibc"
os = "linux"

    [[librealsense.download]]
    sha256 = "b2213b3faf98339a235beba02daa85ec12e8d309b16b52db1a145fb996f01292"
    url = "https://github.com/JuliaBinaryWrappers/librealsense_jll.jl/releases/download/librealsense-v2.38.0+0/librealsense.v2.38.0.aarch64-linux-gnu-cxx03.tar.gz"
[[librealsense]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3008ae6e2b0987f56be82f58f655a457a6844797"
libc = "glibc"
os = "linux"

    [[librealsense.download]]
    sha256 = "8c127bea100eb039495d35a0fcbae44bbb20dfb740d50e6837b28636c67848bc"
    url = "https://github.com/JuliaBinaryWrappers/librealsense_jll.jl/releases/download/librealsense-v2.38.0+0/librealsense.v2.38.0.aarch64-linux-gnu-cxx11.tar.gz"
[[librealsense]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "046123eac0714e86eb2ca67977edbbe853df3ad3"
libc = "glibc"
os = "linux"

    [[librealsense.download]]
    sha256 = "732cb8fa2f700879d862906a5ba6907769ead10909ec819fa54c8522c856e117"
    url = "https://github.com/JuliaBinaryWrappers/librealsense_jll.jl/releases/download/librealsense-v2.38.0+0/librealsense.v2.38.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[librealsense]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "180ccc88ab296be1f8b565e3892f0451f80faf78"
libc = "glibc"
os = "linux"

    [[librealsense.download]]
    sha256 = "5dbefc494d88758c3dc4beeaee894dd088d2c8011963b90b59d0bca5565279b3"
    url = "https://github.com/JuliaBinaryWrappers/librealsense_jll.jl/releases/download/librealsense-v2.38.0+0/librealsense.v2.38.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[librealsense]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0dfaf091f0d48433f25b109b561036d451946e9b"
libc = "glibc"
os = "linux"

    [[librealsense.download]]
    sha256 = "fe656905c89f7f8fac33ef44cb695530622b898f5fb567c84aa4640a57d912b0"
    url = "https://github.com/JuliaBinaryWrappers/librealsense_jll.jl/releases/download/librealsense-v2.38.0+0/librealsense.v2.38.0.i686-linux-gnu-cxx03.tar.gz"
[[librealsense]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4830625213f7bdcfcea014ac2fe82e5ac0591f04"
libc = "glibc"
os = "linux"

    [[librealsense.download]]
    sha256 = "e1b274492588a87fea623d55695c9f8da73d184ccce57fff0fe409c4e6eb97c9"
    url = "https://github.com/JuliaBinaryWrappers/librealsense_jll.jl/releases/download/librealsense-v2.38.0+0/librealsense.v2.38.0.i686-linux-gnu-cxx11.tar.gz"
[[librealsense]]
arch = "x86_64"
git-tree-sha1 = "b11594eb0ecbb010ffc825c5122a6ceec5b49c79"
os = "macos"

    [[librealsense.download]]
    sha256 = "ae7df4bbb1430c6db3183ce5755f55d21b783e31ccc4dfd992771feaedcf6a92"
    url = "https://github.com/JuliaBinaryWrappers/librealsense_jll.jl/releases/download/librealsense-v2.38.0+0/librealsense.v2.38.0.x86_64-apple-darwin.tar.gz"
[[librealsense]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "606c6484548cceeaac7488fa333d5a19ae85caec"
libc = "glibc"
os = "linux"

    [[librealsense.download]]
    sha256 = "240c9d59ec965795a8cf8e0afbc79f1e4b7cbaaec844fbf05262f5e44cfbf1d1"
    url = "https://github.com/JuliaBinaryWrappers/librealsense_jll.jl/releases/download/librealsense-v2.38.0+0/librealsense.v2.38.0.x86_64-linux-gnu-cxx03.tar.gz"
[[librealsense]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e357e78a20e41f3a15408f047eefa794108654ce"
libc = "glibc"
os = "linux"

    [[librealsense.download]]
    sha256 = "ad7caa8d14b97df1780189ac2eb6b8bbc858b3b3144ddecaa8b862f2d8d36ead"
    url = "https://github.com/JuliaBinaryWrappers/librealsense_jll.jl/releases/download/librealsense-v2.38.0+0/librealsense.v2.38.0.x86_64-linux-gnu-cxx11.tar.gz"
