[[librealsense]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "491b92c2129abdc9115a666dc6a8fc1b96f273a6"
libc = "glibc"
os = "linux"

    [[librealsense.download]]
    sha256 = "3ce215060090105a3a553870a49383902e266ffa32a8cfdd7a401fa7662859f8"
    url = "https://github.com/JuliaBinaryWrappers/librealsense_jll.jl/releases/download/librealsense-v2.36.0+0/librealsense.v2.36.0.aarch64-linux-gnu-cxx03.tar.gz"
[[librealsense]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1c5ce93de17fab4140c840d8fe8b42911bc4c4ac"
libc = "glibc"
os = "linux"

    [[librealsense.download]]
    sha256 = "45cc526d27a80016b62405382642eaaaa325c2f507ee19d04902dc1e791aaea6"
    url = "https://github.com/JuliaBinaryWrappers/librealsense_jll.jl/releases/download/librealsense-v2.36.0+0/librealsense.v2.36.0.aarch64-linux-gnu-cxx11.tar.gz"
[[librealsense]]
arch = "armv7l"
cxxstring_abi = "cxx03"
git-tree-sha1 = "58f867ea1c51326556f9743017c758b0a86f9977"
libc = "glibc"
os = "linux"

    [[librealsense.download]]
    sha256 = "37159718e640a005357a726e24b1bb7a391d02472ab0103aba87c6318d7f553e"
    url = "https://github.com/JuliaBinaryWrappers/librealsense_jll.jl/releases/download/librealsense-v2.36.0+0/librealsense.v2.36.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[librealsense]]
arch = "armv7l"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ec4da47a33e3a202d493d5a2e23bbe733a91e718"
libc = "glibc"
os = "linux"

    [[librealsense.download]]
    sha256 = "1573ff199d7a328ad7b8bacbdccf7c756c4dd5eb5bebf72b8995d46e10233448"
    url = "https://github.com/JuliaBinaryWrappers/librealsense_jll.jl/releases/download/librealsense-v2.36.0+0/librealsense.v2.36.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[librealsense]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ed23b7164088c3da16bfb63f77432fb14c195f05"
libc = "glibc"
os = "linux"

    [[librealsense.download]]
    sha256 = "0a396fc9585be8085f7d35b06d9f7c8e9c792ed57c2852655ddefe911e96c902"
    url = "https://github.com/JuliaBinaryWrappers/librealsense_jll.jl/releases/download/librealsense-v2.36.0+0/librealsense.v2.36.0.i686-linux-gnu-cxx03.tar.gz"
[[librealsense]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d02225f761d9e3e48771d4f2dfbae54231675f36"
libc = "glibc"
os = "linux"

    [[librealsense.download]]
    sha256 = "da3a8e39faa3f5fd5c364c508a5c57567c28c6970d3d7b4b5c9ebe9d3f134c2a"
    url = "https://github.com/JuliaBinaryWrappers/librealsense_jll.jl/releases/download/librealsense-v2.36.0+0/librealsense.v2.36.0.i686-linux-gnu-cxx11.tar.gz"
[[librealsense]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c5837e3a753794c206bbbbc30814f8fa33acc632"
os = "macos"

    [[librealsense.download]]
    sha256 = "ffc3b1fa68ff8c62d53e58eb67d9c374b36bb4ec57ee5f90f8fcfab6146fc570"
    url = "https://github.com/JuliaBinaryWrappers/librealsense_jll.jl/releases/download/librealsense-v2.36.0+0/librealsense.v2.36.0.x86_64-apple-darwin14-cxx03.tar.gz"
[[librealsense]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9196f1bbe5ae73e9c936fc3427066c3723a7d9a7"
os = "macos"

    [[librealsense.download]]
    sha256 = "ba3c8863ab2f3e43e638178b306c4834cac6eedaccdad90450feede2bf314220"
    url = "https://github.com/JuliaBinaryWrappers/librealsense_jll.jl/releases/download/librealsense-v2.36.0+0/librealsense.v2.36.0.x86_64-apple-darwin14-cxx11.tar.gz"
[[librealsense]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bb0b90842c2462080fe077039790d2fd33a563eb"
libc = "glibc"
os = "linux"

    [[librealsense.download]]
    sha256 = "2ee6ed23ee0ae7558aa8180d4be55887e26b7cc52bc6717bd17cd1ac7ba7be5c"
    url = "https://github.com/JuliaBinaryWrappers/librealsense_jll.jl/releases/download/librealsense-v2.36.0+0/librealsense.v2.36.0.x86_64-linux-gnu-cxx03.tar.gz"
[[librealsense]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e87c064f94a8bcb89fa18b8f4a7e4cd8464e94d6"
libc = "glibc"
os = "linux"

    [[librealsense.download]]
    sha256 = "5ff443c0e921d10f3e414684c79e4f56b00deccc990a9387cb20a346bb8fa1df"
    url = "https://github.com/JuliaBinaryWrappers/librealsense_jll.jl/releases/download/librealsense-v2.36.0+0/librealsense.v2.36.0.x86_64-linux-gnu-cxx11.tar.gz"
