[[librealsense]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b66e5da1e9aa2ab5a01bc15bee9ecd22fa14a75a"
libc = "glibc"
os = "linux"

    [[librealsense.download]]
    sha256 = "3c00099741f58283878a04da2a200433429a227a696dceb1a9edd3f20849cba9"
    url = "https://github.com/JuliaBinaryWrappers/librealsense_jll.jl/releases/download/librealsense-v2.41.0+0/librealsense.v2.41.0.aarch64-linux-gnu-cxx03.tar.gz"
[[librealsense]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "52778941850684d2e45de7fcc9d949eb228f0874"
libc = "glibc"
os = "linux"

    [[librealsense.download]]
    sha256 = "fbd7e1f0399d6886053940f0db0d80265a698be0d26afaa09ad79c4b25870efe"
    url = "https://github.com/JuliaBinaryWrappers/librealsense_jll.jl/releases/download/librealsense-v2.41.0+0/librealsense.v2.41.0.aarch64-linux-gnu-cxx11.tar.gz"
[[librealsense]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8607e211ce70544263bf0a01eabc8961b8de991b"
libc = "glibc"
os = "linux"

    [[librealsense.download]]
    sha256 = "ec559b7ecd28ddd8946aa8739ade4b20a21beff5ce841e534596e9166b52e4c1"
    url = "https://github.com/JuliaBinaryWrappers/librealsense_jll.jl/releases/download/librealsense-v2.41.0+0/librealsense.v2.41.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[librealsense]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "298adf8194811d6a5908ec38108365c237ace8b9"
libc = "glibc"
os = "linux"

    [[librealsense.download]]
    sha256 = "87416cad0ece92f143e2f2b7ef4173d38164122b3350672c7e36f00fee93d82e"
    url = "https://github.com/JuliaBinaryWrappers/librealsense_jll.jl/releases/download/librealsense-v2.41.0+0/librealsense.v2.41.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[librealsense]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ae48e11cdf1660800c5a5792b649f47eb848db87"
libc = "glibc"
os = "linux"

    [[librealsense.download]]
    sha256 = "19d2ede7d604505099a0e08d5d355cabf8e1ff9861773e05b871bf6dfc15256a"
    url = "https://github.com/JuliaBinaryWrappers/librealsense_jll.jl/releases/download/librealsense-v2.41.0+0/librealsense.v2.41.0.i686-linux-gnu-cxx03.tar.gz"
[[librealsense]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f774ee03ae439ca5e7ddf400ff47c557eb4ab33b"
libc = "glibc"
os = "linux"

    [[librealsense.download]]
    sha256 = "fc5b6242896ae624bee8a9b307db2f6fe6adead381bafda4573f46a655471369"
    url = "https://github.com/JuliaBinaryWrappers/librealsense_jll.jl/releases/download/librealsense-v2.41.0+0/librealsense.v2.41.0.i686-linux-gnu-cxx11.tar.gz"
[[librealsense]]
arch = "x86_64"
git-tree-sha1 = "798332d086e58cf631c36fa75fc0814f52a3e183"
os = "macos"

    [[librealsense.download]]
    sha256 = "8c19686590575763b778079d96c83258db5713a12b6ae52f0167bd074769712f"
    url = "https://github.com/JuliaBinaryWrappers/librealsense_jll.jl/releases/download/librealsense-v2.41.0+0/librealsense.v2.41.0.x86_64-apple-darwin.tar.gz"
[[librealsense]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "922c2a52a42664c30b8658bee1a7653fc369394b"
libc = "glibc"
os = "linux"

    [[librealsense.download]]
    sha256 = "f889c842265f6fae88e77b2989646bc370c666d52886ab134695cd4cb1385d66"
    url = "https://github.com/JuliaBinaryWrappers/librealsense_jll.jl/releases/download/librealsense-v2.41.0+0/librealsense.v2.41.0.x86_64-linux-gnu-cxx03.tar.gz"
[[librealsense]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "57d1ca987125033d1646a588cc1d3229b124b1b8"
libc = "glibc"
os = "linux"

    [[librealsense.download]]
    sha256 = "b0753a8f2165032db87e56af0b3ad4d96fb6d2f54511354ac57213e0e7a85cac"
    url = "https://github.com/JuliaBinaryWrappers/librealsense_jll.jl/releases/download/librealsense-v2.41.0+0/librealsense.v2.41.0.x86_64-linux-gnu-cxx11.tar.gz"
