# Autogenerated wrapper script for librealsense_jll for x86_64-apple-darwin
export librealsense2

using libusb_jll
JLLWrappers.@generate_wrapper_header("librealsense")
JLLWrappers.@declare_library_product(librealsense2, "@rpath/librealsense2.2.41.dylib")
function __init__()
    JLLWrappers.@generate_init_header(libusb_jll)
    JLLWrappers.@init_library_product(
        librealsense2,
        "lib/librealsense2.2.41.0.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
